osx_image: xcode8
language: objective-c

before_install:
- brew update
- if brew outdated | grep -qx carthage; then brew upgrade carthage; fi
- travis_wait 35 carthage bootstrap --platform iOS

script:
- xcodebuild clean build -project Presentation.xcodeproj -scheme "Presentation-iOS" -sdk iphonesimulator
